Test against Ruby 4.0
rdoc is no longer a default gem in 4.0 so we need to include it in the
gemspec. I believe rdoc supports the documentation at
https://www.rubydoc.info/gems/gds-api-adapters/52.3.0. This is only
explicitly used via the Rakefile, so since Rake is a development
dependency, I've made this the same

Output from the 4.0 CI run without adding the gem:

```
home/runner/work/gds-api-adapters/gds-api-adapters/Rakefile:1: warning: rdoc/task is found in rdoc, which is not part of the default gems since Ruby 4.0.0.
You can add rdoc to your Gemfile or gemspec to fix this error.
rake aborted!
LoadError: cannot load such file -- rdoc/task (LoadError)
```