Cast Time.now to_datetime before converting to rfc3339
Without this, getting an error like:
  'NoMethodError: undefined method `rfc3339` for 2019-05-22 07:12:18 +0000:Time'

This wasn't caught before as this was the first time we're calling
'get_subscription_response' with an 'ended: true' parameter.